#配置服务
server:
  port: 9090
#配置数据源
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pm?useUnicode=true&characterEncoding=utf8&serverTimezone=CTT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#指定mybatis映射文件的地址
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.software.**.domain

#pagehelper分页配置
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

logging:
  config: classpath:log/logback.xml